AY2425S1-CS2103T-T09-4/tp

docs/AboutUs.md

AboutUs: Fixed Lutfir's Section

---

README.md

Docs: Update build status badge

---

docs/DeveloperGuide.md

Update user profile, value proposition and user stories in DG

---

docs/DeveloperGuide.md

Update Developer Guide with Use Cases for Help and Clear

---

src/main/java/seedu/address/model/person/Person.java

Person Class: Add fields for parent name and parent contact number

---

src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/MainWindow.fxml
src/main/resources/view/PersonListCard.fxml
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java

Add parent fields to UI and make UI bigger

---

src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java

Storage: Update save functionality to support new fields: parentName, parentPhone, and parentEmail

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Update person constructor

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java

Update Parser to parse new fields in Person object

---

src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/ui/PersonCard.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java

Parser, UI, Storage: Add handling for empty parent arguments 

---

src/main/java/seedu/address/model/tag/Grade.java
src/main/java/seedu/address/model/tag/exceptions/InvalidGradeIndexException.java
src/test/java/seedu/address/model/tag/GradeTest.java

Model: Add grades under tag

---

src/main/java/seedu/address/model/person/ArchivedPersonList.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/test/java/seedu/address/model/person/ArchivedPersonListTest.java
src/test/java/seedu/address/model/person/UniqueAndArchivedPersonListTest.java

Add ArchivedPersonList class. Modify UniquePersonList to interact with new class.
Fixes #76

Archive Feature: Create a new class for archived contacts, interact with UniquePersonList

---

src/main/java/seedu/address/logic/commands/FindTagCommand.java

Remove unnecessary code in find tag

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/GradeCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/GradeCommandParser.java
src/main/java/seedu/address/model/person/Student.java
src/main/java/seedu/address/model/tag/Grade.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/storage/JsonAdaptedStudent.java
src/main/java/seedu/address/ui/StudentCard.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/StudentListCard.fxml
src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/GradeCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/GradeCommandParserTest.java
src/test/java/seedu/address/model/person/StudentTest.java
src/test/java/seedu/address/model/tag/GradeTest.java
src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/StudentBuilder.java
src/test/java/seedu/address/testutil/TypicalStudents.java

Add Grade command

---

docs/UserGuide.md

Update user guide for grade command

---

src/main/java/seedu/address/storage/JsonAdaptedStudent.java

Fix bug with grade

---

src/main/java/seedu/address/model/person/Parent.java
src/test/java/seedu/address/model/person/ParentTest.java
src/test/java/seedu/address/testutil/ParentBuilder.java
src/test/java/seedu/address/testutil/TypicalParents.java

Fixes #67 
Add Parent class to model. Additions not implemented.

Model: Add Parent class

---

src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/HelpWindow.fxml
src/main/resources/view/MainWindow.fxml
src/main/resources/view/PersonListCard.fxml
src/main/resources/view/PersonListPanel.fxml
src/main/resources/view/StudentListCard.fxml

Current UI looks congested as more parameters are being added in
UI needs to look clean and readable
Added columns to utilise horizontal space
Let's make UI readable
Fixes #103

UI: Change UI layout

---

docs/diagrams/BetterModelClassDiagram.puml
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml
src/main/resources/view/StudentListCard.fxml

UI: Add pin icon to pinned users 

---

docs/diagrams/ModelClassDiagram.puml

Archive: Update ModelClassDiagram with ArchivedPersonList

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/PinCommand.java
src/main/java/seedu/address/logic/commands/UnpinCommand.java

Parser: Add assertions to Delete, Pin and Unpin Commands

---

build.gradle
docs/UserGuide.md
src/main/java/seedu/address/MainApp.java

Prepare for 1.4 release

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java

Fix bug for editing education

---

docs/diagrams/BetterModelClassDiagram.puml

Diagram: update UML 

---

docs/UserGuide.md

1. Update command summary to include the following commands:
-   List archive
-   Archive
-   Unarchive
-   Pin
-   Unpin
-   List students
2. Add command explanation for list students

User Guide: Update command summary

---

docs/UserGuide.md

Add introduction to user guide

---

src/main/java/seedu/address/logic/commands/LinkCommand.java
src/main/java/seedu/address/logic/commands/PinCommand.java
src/main/java/seedu/address/logic/commands/UnlinkCommand.java
src/main/java/seedu/address/model/person/Parent.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/Student.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/ui/PersonCard.java
src/test/java/seedu/address/testutil/PersonBuilder.java

Fix isPinned Method Name

---

src/main/java/seedu/address/logic/commands/ListParentsCommand.java
src/main/java/seedu/address/logic/commands/ListStudentsCommand.java

Fix List Commands

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/LinkCommand.java
src/main/java/seedu/address/logic/commands/UnlinkCommand.java
src/main/java/seedu/address/logic/parser/AddParentCommandParser.java
src/main/java/seedu/address/model/person/Parent.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedParent.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/java/seedu/address/model/person/ParentTest.java
src/test/java/seedu/address/testutil/ParentBuilder.java

Change parent to accept multiple children

---

docs/DeveloperGuide.md
docs/diagrams/BetterModelClassDiagram.puml
docs/diagrams/ModelClassDiagram.puml
docs/diagrams/UiClassDiagram.puml

Fixes #164 
Fixes #165 
Fixes #163

Update developer guide

---

src/main/java/seedu/address/model/person/Phone.java
src/main/java/seedu/address/model/tag/Education.java

Update restrictions for user inputs

---

docs/UserGuide.md

Added caution to delete command

Update UG: Delete command

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/AddParentCommand.java
src/main/java/seedu/address/logic/commands/AddStudentCommand.java

Change adds and addp command words

---

docs/DeveloperGuide.md

Update DG: Manual Testing

---

src/main/java/seedu/address/logic/commands/EditCommand.java

Fix EditCommand removing pin and archive

---

docs/UserGuide.md

Fix #265 #271 #227 #282 #281 #251 #288 #253 #294 #241 #239 #230 #236 #232 #243 #272 #290 #256 #257 #262 #298 #264 #295 #268 #278
Note: Screenshots are not updated, tips haven't been added yet

UG: Fix UG command errors

---

src/main/java/seedu/address/logic/parser/LinkCommandParser.java

Fix Parsing Error with LinkCommand

---

src/main/java/seedu/address/storage/JsonAdaptedParent.java

Fix bug from null children in storage

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java

Fix bug from repeated indices in delete command

---

docs/UserGuide.md
src/main/java/seedu/address/model/tag/Grade.java

Fixes #249
Fixes #245
Fixes #237

Fix grade error message

---

src/main/java/seedu/address/logic/commands/EditCommand.java

Fixes #275 
Fixes #266
Fixes #240

Fix edit not updating links

---

docs/UserGuide.md

Screenshots are **NOT** updated

UG: Change Intro, Reformat UG
